added support for athrow and dup_x1 op codes and ginstance, only for object types
rahulmutt/codec-jvm pull request #3
Opened 2017-02-02 15:39 UTC by Curdled

2017-02-02 15:41 UTC, rahulmutt commented on src/Codec/JVM/ASM/Code.hs
> +  IT.withOffset $ \offset -> fold
You don't use `offset` anywhere - is this intended?

2017-02-02 20:40 UTC, joseph-isaacs reviewed
Change the ginstance to use mkCode

2017-02-15 05:40 UTC, rahulmutt requested changes

2017-02-15 05:40 UTC, rahulmutt commented on src/Codec/JVM/ASM/Code.hs
> +
Swap the ordering of `pop ft2` and `pop ft1` and I'll merge.

2017-02-20 17:12 UTC, Curdled commented on src/Codec/JVM/ASM/Code.hs
> +
Fixed

2017-02-20 17:17 UTC, rahulmutt commented
It's hard for me to see what changes you did. Can you close this pull request and open a new one (after  rebasing your fork)?

2017-02-22 10:27 UTC, closed without merging